config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :users
  resources :posts
  resources :sessions, only: [:new, :create, :destroy]

  root "posts#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 #  devise :database_authenticatable, :registerable,
 #         :recoverable, :rememberable, :trackable, :validatable

	# validate :title, presence: true, length: {minimum: 8}
	# validate :body, presence: true
		# attr_accessible :title, :body


 # validation & error messages with andrewperk
		validates :title, :body, presence: true
		validates :title, :length => { :minimum => 2, maximum: 50 }
		validates :title, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	# scope :with_last_name_caraballo, -> {where(lname: "Caraballo")}
	# scope :with_last_name_orlando, -> lamdba {where(fname: "Orlando")}
	# scipe :hotmail, -> {wgere(email: "horatio%hotmail.com ")}
	# scope :starts_with_p, -> {where("fname LIKE ?", "P%")}
	validates_confirmation_of :password
	validates_presence_of :password, :on => :create
	validates_presence_of :email
	validates_uniqueness_of :email

	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png" validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/


	#lesson on data integrity to change for STATUS ={"active", "inactive", "banned"}
	def edit
		@user = User.find params[:id]

		@user.status = Status[0]
		@user.save
	end
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	
	after_destroy :log_destroy_action

	# @posts is a variable that is going to be available in the index.html.erb page
	def index
		@posts = Post.all.order('created_at DESC')
	end

  def log_destroy_action
    puts 'Post destroyed'
  end

	def new
		@post = Post.new
	end


	def create
		@post = Post.new(post_params)
		@post.save
		redirect_to @post
	end

	def show
		@post = Post.find(params[:id])
	end

	def delete
		 @post = Post.find(params[:id])
	   @post.delete
	end

	def destroy
  	 session[:user_id] = nil
     redirect_to post_path
	end


# private prevents you from doing a mass update (will not be able to use one line of code to create/update a user)in these fields
	private
	def post_params
		params.require(:post).permit(:title, :body)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	@user = User.new(params[:user])
	if @user.save
    flash[:notice] = "Your account was created
    successfully."
    redirect_to user_path @post
	else
	    flash[:alert] = "There was a problem saving your
	    account."
	    redirect_to session_path
	end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def create
		@user = User.create(user_params)
		# @user = user.start_with_p  can i place it here instead of insea
	end

	def new
	end

private
	def users_params
	params.require(:user).permit(:fname, :lname, :email)
	end

	def delete
	end

	def Submitting
		respond_to do |format|
			format.js
		end

		alert ('submit')
	end

	# def caraballo
	# 	@users = User.with_last_name_craballo.with_first_name_orlando
	# end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	#generates <h1><em>title</em></h1>
	def custom_h1_tag(title)
		content_tag(:h1) do 
			content_tag(:em, title) 
		end
	end
	def custom_p_tag(title)
		content_tag(:p) do 
			content_tag(:strong, title) 
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/layouts/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
    <br>
    <%= f.label :body %><br>
    <%= f.text_area :body %><br>
    <br>
    <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BasicBlogRails</title>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
	<script src="cookies.js"></script>
	<script src="/scripts/cookieset.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <% stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Corben:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="sidebar">
		<div id="logo">
			<%= link_to root_path do %>
			<%= image_tag "logo.svg" %>
			<% end %>
		</div>

		<ul>
			<li class="category">Website</li>
			<li><%= link_to "Blog", root_path %></li>
			<li>About</li>
		</ul>

		<ul>
			<li class="category">Social</li>
			<li>
				<a href="https://twitter.com">Twitter</a></li>
		</ul>

		<p class="sign_in">Login</p>
	</div>

	<div id="main_content">
		<div id="header">
			<% if current_page?(root_path) %>
				<p>All Posts</p>
			<% elsif current_page?(root_path) %>
				<p>About</p>
			<% else %>
				<%= link_to "Back to All Posts", root_path %>
			<% end %>
			
			<%# if user_signed_in? %>
			
			<!-- <p>All Post</p> -->

			<div class="buttons">
				<button class="button"><%= link_to "New Post", new_post_path %></button>
				<button class="button"><Logout>Log Out</button>
			</div>
		</div>
	
	<% flash.each do |name, msg| %>
	<%= content_tag(:div, msg, class: "alert") %>
		<% end %>
	<%= yield %>
	</div>
	


</body>

</html>

app/views/layouts/edit.html.erb
<div> id="page wrapper">
	<h1> Edit Post </h1>

	<%= render 'form' %>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for @post do |f|
<% if @post.errors.any? %>
	<h2>Errors:</h2>
	<ul>
		<% @post.errors.full_messages.each do |message| %>
		<li><%= message %></li>
	<% end %>
	</ul>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %><br>
	</p>
	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %><br>
	</p>
	  <%= f.submit "Add a New Post" %>
	</p>
<% end %>

app/views/posts/index.html.erb
<% @posts.each do|post| %>
 <div class="post_wrapper">
 	<h2 class="title"><%= link_to post.title, post %></h2>
 	<p class="date"><%= post.created_at.strftime("%B %d, %Y") %></p>
 </div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
<h1>New Post Today</h1>

<%= form_for :post, url: posts_path do |f| %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %><br>
	</p>

	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %><br>
	</p>

	<p>
		<%= f.submit %>
	</p>

<% end %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
	<%= custom_h1_tag @post.title %>

	<%=link_to "Delete", post_path(@post), method: :delete, remote: true, class: "delete-post" %>



<!-- below is using a view helper to write html into page. custom_p_tag was created in the Post_Helper.rb file; you do not need the <p> tags -->

	<h5>Submitted</h5> <%= custom_p_tag time_ago_in_words(@post.created_at) %>Ago 
	
		
	


</div>

app/views/users/new.html.erb
<%= form_for @user, :url => users_path, :html => { :multipart => true } do |form| %>
<%= form.label :fname %> 
<%= form.text_field :fname %>
<%= form.label :lname %> 
<%= form.text_field :lname %> 
<%= form.file_field :avatar %> 
<%= form.submt %>
<% end %>